export { default as HomePage } from './HomePage/HomePage';
export { default as NewsAllPage } from './NewsAllPage/NewsAllPage';
export { default as NewsMaintenancePage } from './NewsMaintenancePage/NewsMaintenancePage';
export { default as NewsNoticesPage } from './NewsNoticesPage/NewsNoticesPage';
export { default as NewsUpdatesPage } from './NewsUpdatesPage/NewsUpdatesPage';
export { NewsDetailPage, newsDetailsLoader  } from './NewsDetailsPage/index';
export { default as DownloadPage } from './DownloadPage/DownloadPage';
export { default as LoginPage } from './LoginPage/LoginPage';
export { default as SignupPage } from './SignupPage/SignupPage';
export { default as InquiryPage } from './InquiryPage/InquiryPage';
export { default as InquiriesPage } from './InquiriesPage/InquiriesPage';
export { default as ErrorPage } from './ErrorPage/ErrorPage';