export { default as HomePage } from './HomePage/HomePage';
export { NewsPage } from './NewsPage/index';
export { NewsDetailPage } from './NewsDetailsPage/index';
export { DownloadPage, downloadPageLoader } from './DownloadPage/index';
export { LoginPage, loginPageLoader } from './LoginPage/index';
export { default as SignupPage } from './SignupPage/SignupPage';
export { default as InquiryPage } from './InquiryPage/InquiryPage';
export { InquiriesPage, inquiriesPageLoader } from './InquiriesPage/index';
export { InquiriesDetailPage, inquiriesDetailsLoader } from './InquiriesDetailsPage/index';
export { default as ErrorPage } from './ErrorPage/ErrorPage';